### ISSUE TITLE
[Question] Explaination for indices in Spectrogram.js -> movingAverage [Line 44 and Line 45]

### ISSUE THREAD

**Issue by aklagoo** [SumianVoice/spectrus-js-the-second#18]
FYI, these changes did not seem to affect the spectrogram in any way.

**Line 44:**
```javascript
    for (let l = i - span; l < i + span; l++) {
```
Are we considering an even window here? Or should the comparison be changed to ```l <= i + span;```?

**Line 46:**
```javascript
      if (l > 0 && l < Math.min(array.length, maxIndex)) {
```
Should ```l > 0``` be changed to ```l >= 0```?

**Comment by SumianVoice** [comment]
Yep seems like off by one thanks for the heads up
