### ISSUE TITLE
Weird behavior with viewport resize

### ISSUE THREAD

**Issue by hle0** [SumianVoice/spectrus-js-the-second#4]
See gif. Some of the stuff gets scaled improperly, or gets tied to the previous viewport size
![sumi-2022-06-09_09 36 53](https://user-images.githubusercontent.com/91701075/172860898-50d25839-6681-494c-a575-7270144f2c35.gif)
.

**Comment by SumianVoice** [comment]
fixed in [commit](https://github.com/SumianVoice/spectrus-js-the-second/commit/2c64dc5285a806662530467dbf496f1551a0d792)

CSS rules were scaling the canvas for some reason
